# Generated by Django 4.1.4 on 2022-12-13 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliver.box')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliver.order'),
        ),
    ]
