# Generated by Django 4.1.4 on 2022-12-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='boxes',
            field=models.CharField(default='', max_length=255),
        ),
    ]
