# Generated by Django 4.1.4 on 2022-12-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0002_order_boxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='boxes',
        ),
    ]
