# Generated by Django 4.1.4 on 2022-12-13 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0003_remove_order_boxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='deliver.order'),
        ),
        migrations.RemoveField(
            model_name='good',
            name='box',
        ),
        migrations.AddField(
            model_name='good',
            name='box',
            field=models.ManyToManyField(related_name='goods', to='deliver.box'),
        ),
    ]
